export interface StockItem {
	symbol?: string | number
	code: string | number
	market: string | null
	cName: string
	tier: number | null
	number: number
	financeHealth: number | null
	description: string | null
}

export const stockList: StockItem[] = [
	{ code: '00700', market: null, cName: '腾讯控股', tier: 0, number: 900, financeHealth: null, description: null },
	{ code: '01810', market: null, cName: '小米集团', tier: 1.5, number: 8600, financeHealth: null, description: null },
	{ code: '000661', market: null, cName: '长春高新', tier: 3, number: 0, financeHealth: 83, description: null },
	{ symbol: 'sh601615', code: 601615, market: null, cName: '明阳智能', tier: 1.5, number: 0, financeHealth: 57, description: null },
	{ code: 300274, market: null, cName: '阳光电源', tier: 1.5, number: 0, financeHealth: 75, description: null },
	{ code: 603606, market: null, cName: '东方电缆', tier: 1.5, number: 0, financeHealth: 86, description: null },
	{ code: 163415, market: null, cName: '兴全模式', tier: 2, number: 0, financeHealth: null, description: null },
	{ code: 161005, market: null, cName: '富国天惠', tier: 2, number: 0, financeHealth: null, description: null },
	{ code: 601012, market: null, cName: '隆基绿能', tier: 1.5, number: 0, financeHealth: 76, description: null },
	{ code: 600438, market: null, cName: '通威股份', tier: 3, number: 0, financeHealth: 53, description: null },
	{ code: '002080', market: null, cName: '中材科技', tier: 2.5, number: 0, financeHealth: 62, description: null },
	{ code: 9626, market: null, cName: '哔哩哔哩', tier: 2, number: 0, financeHealth: null, description: null },
	{ code: 2150, market: null, cName: '奈雪的茶', tier: 2, number: 6000, financeHealth: null, description: null },
	{ code: 300059, market: null, cName: '东方财富', tier: 2.5, number: 0, financeHealth: 51, description: null },
	{ code: '002271', market: null, cName: '东方雨虹', tier: 2.5, number: 0, financeHealth: 82, description: null },
	{ code: '601888', market: null, cName: '中国中免', tier: 1.5, number: 200, financeHealth: 94, description: null },
	{ code: '600519', market: null, cName: '贵州茅台', tier: 3, number: 0, financeHealth: 95, description: null },
	{ code: '000858', market: null, cName: '五粮液', tier: 3, number: 0, financeHealth: 88, description: null },
	{ code: 515790, market: null, cName: '光伏ETF', tier: 2, number: 0, financeHealth: null, description: null },
	{ code: 512400, market: null, cName: '有色ETF', tier: 2.5, number: 0, financeHealth: null, description: null },
	{ code: 515210, market: null, cName: '钢铁ETF', tier: 2.5, number: 0, financeHealth: null, description: null },
	{ code: 516020, market: null, cName: '化工ETF', tier: 2.5, number: 0, financeHealth: null, description: null },
	{ code: 515220, market: null, cName: '煤炭ETF', tier: 2.5, number: 0, financeHealth: null, description: null },
	{ code: 163406, market: null, cName: '兴全合润', tier: 2, number: 0, financeHealth: null, description: null },
	{ code: 501054, market: null, cName: '东证睿泽', tier: 2, number: 0, financeHealth: null, description: null },
	{ code: 163417, market: null, cName: '兴全合宜', tier: 2, number: 0, financeHealth: null, description: null },
	{ code: '002487', market: null, cName: '大金重工', tier: 2.5, number: 0, financeHealth: 67, description: null },
	{ code: 688186, market: null, cName: '广大特材', tier: 2, number: 800, financeHealth: 41, description: null },
	{ code: 300443, market: null, cName: '金雷股份', tier: 2.5, number: 0, financeHealth: 92, description: null },
	{ code: 600905, market: null, cName: '三峡能源', tier: 2.5, number: 0, financeHealth: 61, description: null },
	{ code: 601016, market: null, cName: '节能风电', tier: 2.5, number: 0, financeHealth: 55, description: null },
	{ code: 603985, market: null, cName: '恒润股份', tier: 2, number: 0, financeHealth: 88, description: null },
	{ code: 603218, market: null, cName: '日月股份', tier: 2.5, number: 0, financeHealth: 84, description: null },
	{ code: 603298, market: null, cName: '杭叉集团', tier: 2, number: 0, financeHealth: 91, description: null },
	{ code: '002028', market: null, cName: '思源电气', tier: 2.5, number: 0, financeHealth: 90, description: null },
	{ code: 603916, market: null, cName: '苏博特', tier: 2, number: 0, financeHealth: 66, description: null },
	{ code: '002241', market: null, cName: '歌尔股份', tier: 3, number: 0, financeHealth: 48, description: null },
	{ code: '002475', market: null, cName: '立讯精密', tier: 3, number: 0, financeHealth: 71, description: null },
	{ code: 588000, market: null, cName: '科创50', tier: 2, number: 0, financeHealth: null, description: null },
	{ code: 502000, market: null, cName: '500增强', tier: 2.5, number: 0, financeHealth: null, description: null },
	{ code: 600036, market: null, cName: '招商银行', tier: 1.5, number: 600, financeHealth: 68, description: null },
	{ code: 300750, market: null, cName: '宁德时代', tier: 3, number: 0, financeHealth: 72, description: null },
	{ code: 300014, market: null, cName: '亿纬锂能', tier: 2.5, number: 0, financeHealth: 82, description: null },
	{ code: '002812', market: null, cName: '恩捷股份', tier: 2, number: 0, financeHealth: 65, description: null },
	{ code: 300015, market: null, cName: '爱尔眼科', tier: 2.5, number: 0, financeHealth: 76, description: null },
	{ code: 688050, market: null, cName: '爱博医疗', tier: 2.5, number: 0, financeHealth: null, description: null },
	{ code: 300896, market: null, cName: '爱美客', tier: 2, number: 0, financeHealth: 80, description: null },
	{ code: 300124, market: null, cName: '汇川技术', tier: 2.5, number: 0, financeHealth: 74, description: null },
	{ code: 603650, market: null, cName: '彤程新材', tier: 3, number: 0, financeHealth: 63, description: null },
	{ code: 2269, market: null, cName: '药明生物', tier: 3, number: 0, financeHealth: null, description: null },
	{ code: 603259, market: null, cName: '药明康德', tier: 3, number: 0, financeHealth: 81, description: null },
	{ code: 512880, market: null, cName: '证券etf', tier: 3, number: 0, financeHealth: null, description: null },
	{ code: 600887, market: null, cName: '伊利股份', tier: 3, number: 0, financeHealth: 73, description: null },
	{ code: 688363, market: null, cName: '华熙生物', tier: 3, number: 0, financeHealth: null, description: null },
	{ code: 600089, market: null, cName: '特变电工', tier: 3, number: 0, financeHealth: 47, description: null },
	{ code: '000400', market: null, cName: '许继电气', tier: 3, number: 0, financeHealth: 67, description: null },
	{ code: 601100, market: null, cName: '恒立液压', tier: 3, number: 0, financeHealth: 95, description: null },
	{ code: '002709', market: null, cName: '天赐材料', tier: 3, number: 0, financeHealth: 73, description: null },
	{ code: 300751, market: null, cName: '迈为股份', tier: 3, number: 0, financeHealth: 73, description: null },
	{ code: 300595, market: null, cName: '欧普康视', tier: 3.5, number: 0, financeHealth: 95, description: null },
	{ code: 300763, market: null, cName: '锦浪科技', tier: 3, number: 0, financeHealth: 84, description: null },
	{ code: 300850, market: null, cName: '新强联', tier: 2, number: 0, financeHealth: 61, description: null },
	{ code: 601058, market: null, cName: '赛轮轮胎', tier: 3, number: 400, financeHealth: 50, description: null },
	{ code: 513330, market: null, cName: '恒生互联', tier: 1.5, number: 128600, financeHealth: null, description: null },
	{ code: 513180, market: null, cName: '恒生科技', tier: 1.5, number: 0, financeHealth: null, description: null },
	{ code: 301071, market: null, cName: '力量钻石', tier: 2, number: 0, financeHealth: 84, description: null },
	{ code: 6078, market: null, cName: '海吉亚', tier: null, number: 0, financeHealth: null, description: null },
	{ code: 6049, market: null, cName: '保利物业', tier: null, number: 0, financeHealth: null, description: null },
	{ code: 9992, market: null, cName: '泡泡玛特', tier: null, number: 0, financeHealth: null, description: null },
	{ code: 603105, market: null, cName: '芯能科技', tier: 3, number: 0, financeHealth: 41, description: null },
]
